INSERT INTO USER (USER_ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES (1, 'admin', '$2a$10$7ohB6RaNlwExCnVJ0FEGpeZ9WzUvozzWApm4SlQjo4rC1KbShOLla', 'admin', 1);
INSERT INTO USER (USER_ID, USERNAME, PASSWORD, NICKNAME, ACTIVATED) VALUES (2, 'user', '$2a$10$y8b7pzz3zMJQWxocDPM6nu32E8QXmgcAqmFnM5/vsMju/Zj3.WmgG', 'user', 1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (2, 'ROLE_USER');

INSERT INTO STUDY_TIME (USERNAME, TIME, DATE) values ('admin', 7200 ,sysdate());
INSERT INTO STUDY_TIME (USERNAME, TIME, DATE) values ('user', 7200 ,sysdate());